# For simplicity â€“ mailer bundle dropped mailer_user parameter after Symfony 3 -> Symfony 4
parameters:
    mailer_user: "no-replay@nfqakademija.lt"

# By example from https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"